version: '3.7'

services:
    database:
        image: mongo
        container_name: "mongodb"
        restart: unless-stopped
        hostname: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=ayaya_lord
            - MONGO_INITDB_ROOT_PASSWORD=h4ck3r
        volumes:
            - database:/data/db
        ports:
            - 27017:27017
    bot:
        build: ./
        image: phonewave
        container_name: phonewave
        hostname: phonewave
        restart: unless-stopped
        # This make me questions if we need .env 
        environment:
            - MONGO_HOST=mongo
            - MONGO_USERNAME=ayaya_lord
            - MONGO_PASSWORD=h4ck3r
            - MONGO_PORT=27017
        depends_on:
            - database

volumes:
    database:
