version: '3.7'

services:
    mongo:
        image: mongo
        restart: unless-stopped
        hostname: mongo
        environment:
            - MONGO_INITDB_DATABASE=phonewave
            - MONGO_INITDB_ROOT_USERNAME=phonewave
            - MONGO_INITDB_ROOT_PASSWORD=changeme
        volumes:
            - mongo:/data/db
        ports:
            - "27017:27017" # https://www.mongodb.com/docs/manual/reference/default-mongodb-port/
    bot:
        build: .
        image: phonewave
        hostname: bot
        restart: unless-stopped
        # This make me questions if we need .env 
        environment:
            - MONGO_HOST=mongo
            - MONGO_USERNAME=phonewave
            - MONGO_PASSWORD=changeme
            - MONGO_PORT=27017
        depends_on:
            - mongo

volumes:
    mongo:
